name: quarto rendering

on:
#  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
      
    steps:
    - uses: quarto-dev/quarto-actions/setup@v2
  
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version:  4.2.0
        
    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages:
          any::knitr
          any::rmarkdown
          any::jsonlite
         
    - run: ls -al docs
    
    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
        
    - run: ls -al docs
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Render Quarto
